import * as fs from 'fs';
import * as path from 'path';
import { PROGRAMS as CURRENT_PROGRAMS, Program } from '../src/data/programs';

// We want to combine and enrich CURRENT_PROGRAMS with all the verified programs from the prompt.
// We also want to normalize duplicates into preferred displayNames with aliases.

interface RawProgramInput {
  displayName: string;
  degree: string;
  name: string;
  specialization?: string;
  shortName: string;
  aliases: string[];
  category: 'engineering' | 'arts_science';
  group: string;
  source?: string;
}

// Master list based on sections 3 to 15 of user prompt:
export const MASTER_INPUTS: RawProgramInput[] = [
  // ── 3. ENGINEERING / TECHNOLOGY ──
  // CIVIL
  {
    displayName: 'B.E. Civil Engineering',
    degree: 'B.E.',
    name: 'Civil Engineering',
    shortName: 'CIVIL',
    aliases: ['Civil', 'Civil Engg', 'BE Civil', 'B.E Civil'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Geoinformatics Engineering',
    degree: 'B.E.',
    name: 'Geoinformatics Engineering',
    shortName: 'GEO',
    aliases: ['B.E. Geo Informatics Engineering', 'B.E. Geoinformatics', 'Geo Informatics', 'Geoinformatics', 'GIS'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Environmental Engineering',
    degree: 'B.E.',
    name: 'Environmental Engineering',
    shortName: 'ENV',
    aliases: ['Environmental', 'BE Environmental', 'B.E Environmental Engineering'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Civil Engineering (Environmental Engineering)',
    degree: 'B.E.',
    name: 'Civil Engineering',
    specialization: 'Environmental Engineering',
    shortName: 'CIVIL (Env)',
    aliases: ['Civil Environmental', 'B.E. Civil (Environmental Engineering)'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Environmental Science and Technology',
    degree: 'B.E.',
    name: 'Environmental Science and Technology',
    shortName: 'EST',
    aliases: ['Environmental Science', 'B.E Environmental Science and Technology'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.Arch. Architecture',
    degree: 'B.Arch.',
    name: 'Architecture',
    shortName: 'B.Arch',
    aliases: ['B.Arch.', 'B.Arch', 'Architecture', 'Bachelor of Architecture'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.Plan. Bachelor of Planning',
    degree: 'B.Plan.',
    name: 'Planning',
    shortName: 'B.Plan',
    aliases: ['B.Plan.', 'B.Plan', 'Bachelor of Planning', 'Town Planning'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },
  {
    displayName: 'B.Des. Bachelor of Design',
    degree: 'B.Des.',
    name: 'Design',
    shortName: 'B.Des',
    aliases: ['B.Des.', 'B.Des', 'Bachelor of Design', 'Design'],
    category: 'engineering',
    group: 'CIVIL',
    source: 'Anna University',
  },

  // MECHANICAL
  {
    displayName: 'B.E. Mechanical Engineering',
    degree: 'B.E.',
    name: 'Mechanical Engineering',
    shortName: 'MECH',
    aliases: ['Mechanical', 'Mech Engg', 'BE Mechanical', 'B.E Mech'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Materials Science and Engineering',
    degree: 'B.E.',
    name: 'Materials Science and Engineering',
    shortName: 'MSE',
    aliases: ['Materials Science', 'B.E Materials Science and Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Mining Engineering',
    degree: 'B.E.',
    name: 'Mining Engineering',
    shortName: 'MINING',
    aliases: ['Mining', 'B.E Mining Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Printing and Packaging Technology',
    degree: 'B.E.',
    name: 'Printing and Packaging Technology',
    shortName: 'PRINT',
    aliases: ['Printing Technology', 'Packaging Technology', 'B.E Printing and Packaging Technology'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Manufacturing Engineering',
    degree: 'B.E.',
    name: 'Manufacturing Engineering',
    shortName: 'MFG',
    aliases: ['Manufacturing', 'B.E Manufacturing Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Industrial Engineering',
    degree: 'B.E.',
    name: 'Industrial Engineering',
    shortName: 'IE',
    aliases: ['Industrial', 'B.E Industrial Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Aeronautical Engineering',
    degree: 'B.E.',
    name: 'Aeronautical Engineering',
    shortName: 'AERO',
    aliases: ['Aeronautical', 'Aero', 'B.E Aeronautical Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Automobile Engineering',
    degree: 'B.E.',
    name: 'Automobile Engineering',
    shortName: 'AUTO',
    aliases: ['Automobile', 'Auto Engg', 'B.E Automobile Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Production Engineering',
    degree: 'B.E.',
    name: 'Production Engineering',
    shortName: 'PROD',
    aliases: ['Production', 'B.E Production Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Robotics and Automation Engineering',
    degree: 'B.E.',
    name: 'Robotics and Automation Engineering',
    shortName: 'ROBOTICS',
    aliases: ['B.E. Robotics and Automation', 'Robotics', 'Automation', 'Robotics Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Mechatronics Engineering',
    degree: 'B.E.',
    name: 'Mechatronics Engineering',
    shortName: 'MECHATRONICS',
    aliases: ['Mechatronics', 'B.E Mechatronics Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Mechanical and Automation Engineering',
    degree: 'B.E.',
    name: 'Mechanical and Automation Engineering',
    shortName: 'MAE',
    aliases: ['Mechanical and Automation', 'B.E Mechanical and Automation Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Industrial Engineering and Management',
    degree: 'B.E.',
    name: 'Industrial Engineering and Management',
    shortName: 'IEM',
    aliases: ['IEM', 'B.E Industrial Engineering and Management'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Marine Engineering',
    degree: 'B.E.',
    name: 'Marine Engineering',
    shortName: 'MARINE',
    aliases: ['Marine', 'B.E Marine Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Aerospace Engineering',
    degree: 'B.E.',
    name: 'Aerospace Engineering',
    shortName: 'AEROSPACE',
    aliases: ['Aerospace', 'B.E Aerospace Engineering'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Mechanical Engineering (Specialized in Automobile)',
    degree: 'B.E.',
    name: 'Mechanical Engineering',
    specialization: 'Automobile',
    shortName: 'MECH (Auto)',
    aliases: ['Mechanical Automobile', 'B.E. Mechanical (Automobile)'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Mechanical Engineering (Specialized in Smart Manufacturing)',
    degree: 'B.E.',
    name: 'Mechanical Engineering',
    specialization: 'Smart Manufacturing',
    shortName: 'MECH (Smart Mfg)',
    aliases: ['Smart Manufacturing', 'B.E. Mechanical (Smart Manufacturing)'],
    category: 'engineering',
    group: 'MECHANICAL',
    source: 'Anna University',
  },

  // ELECTRICAL / ELECTRONICS
  {
    displayName: 'B.E. Electrical and Electronics Engineering',
    degree: 'B.E.',
    name: 'Electrical and Electronics Engineering',
    shortName: 'EEE',
    aliases: ['EEE', 'Electrical', 'B.E EEE', 'B.E Electrical and Electronics Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electrical and Computer Engineering',
    degree: 'B.E.',
    name: 'Electrical and Computer Engineering',
    shortName: 'ECompE',
    aliases: ['Electrical and Computer', 'B.E Electrical and Computer Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electronics and Instrumentation Engineering',
    degree: 'B.E.',
    name: 'Electronics and Instrumentation Engineering',
    shortName: 'EIE',
    aliases: ['EIE', 'Instrumentation', 'B.E Electronics and Instrumentation Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Instrumentation and Control Engineering',
    degree: 'B.E.',
    name: 'Instrumentation and Control Engineering',
    shortName: 'ICE',
    aliases: ['ICE', 'Instrumentation and Control', 'B.E Instrumentation and Control Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electrical and Electronics Engineering (Training Integrated Programme)',
    degree: 'B.E.',
    name: 'Electrical and Electronics Engineering',
    specialization: 'Training Integrated Programme',
    shortName: 'EEE (Sandwich)',
    aliases: ['EEE Training Integrated', 'EEE Sandwich', 'B.E. EEE (Training Integrated Programme)'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electronics and Communication Engineering',
    degree: 'B.E.',
    name: 'Electronics and Communication Engineering',
    shortName: 'ECE',
    aliases: ['ECE', 'Electronics', 'B.E ECE', 'B.E Electronics and Communication Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Biomedical Engineering',
    degree: 'B.E.',
    name: 'Biomedical Engineering',
    shortName: 'BME',
    aliases: ['BME', 'Biomedical', 'B.E BME', 'B.E Biomedical Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Medical Electronics',
    degree: 'B.E.',
    name: 'Medical Electronics',
    shortName: 'MedElec',
    aliases: ['Medical Electronics', 'B.E Medical Electronics'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electronics and Computer Engineering',
    degree: 'B.E.',
    name: 'Electronics and Computer Engineering',
    shortName: 'ECE (Comp)',
    aliases: ['Electronics and Computer', 'B.E Electronics and Computer Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Electronics and Telecommunication Engineering',
    degree: 'B.E.',
    name: 'Electronics and Telecommunication Engineering',
    shortName: 'ETE',
    aliases: ['Telecommunication', 'B.E Electronics and Telecommunication Engineering'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Electronics Engineering (VLSI Design and Technology)',
    degree: 'B.Tech.',
    name: 'Electronics Engineering',
    specialization: 'VLSI Design and Technology',
    shortName: 'VLSI',
    aliases: ['VLSI', 'VLSI Design', 'B.Tech VLSI', 'B.E. VLSI', 'Electronics Engineering VLSI'],
    category: 'engineering',
    group: 'ELECTRICAL / ELECTRONICS',
    source: 'Anna University',
  },

  // COMPUTER / IT
  {
    displayName: 'B.E. Computer Science and Engineering',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    shortName: 'CSE',
    aliases: ['CSE', 'Computer Science', 'BE CSE', 'B.E CSE', 'B.E Computer Science and Engineering'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer and Communication Engineering',
    degree: 'B.E.',
    name: 'Computer and Communication Engineering',
    shortName: 'CCE',
    aliases: ['CCE', 'Computer and Communication', 'B.E Computer and Communication Engineering'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Engineering (Data Science)',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    specialization: 'Data Science',
    shortName: 'CSE (DS)',
    aliases: ['CSE DS', 'CSE Data Science', 'Data Science Engineering', 'B.E. CSE (Data Science)'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Engineering (Cyber Security)',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    specialization: 'Cyber Security',
    shortName: 'CSE (CS)',
    aliases: ['CSE CS', 'CSE Cyber Security', 'Cyber Security', 'Cyber', 'B.E. CSE (Cyber Security)'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Engineering (Internet of Things)',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    specialization: 'Internet of Things',
    shortName: 'CSE (IoT)',
    aliases: ['CSE IoT', 'CSE (IoT)', 'IoT', 'Internet of Things', 'B.E. CSE (IoT)', 'B.E. CSE (Internet of Things)'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Engineering (Artificial Intelligence)',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    specialization: 'Artificial Intelligence',
    shortName: 'CSE (AI)',
    aliases: ['CSE AI', 'CSE Artificial Intelligence', 'AI Engineering', 'B.E. CSE (AI)'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Engineering (Artificial Intelligence and Machine Learning)',
    degree: 'B.E.',
    name: 'Computer Science and Engineering',
    specialization: 'Artificial Intelligence and Machine Learning',
    shortName: 'CSE (AIML)',
    aliases: ['CSE AIML', 'CSE AI ML', 'AI and Machine Learning', 'AIML', 'B.E. CSE (AIML)'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Computer Science and Design',
    degree: 'B.E.',
    name: 'Computer Science and Design',
    shortName: 'CSD',
    aliases: ['CSD', 'Computer Science and Design', 'B.E Computer Science and Design'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Information Technology',
    degree: 'B.Tech.',
    name: 'Information Technology',
    shortName: 'IT',
    aliases: ['IT', 'Info Tech', 'B.Tech IT', 'B.Tech Information Technology'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Artificial Intelligence and Data Science',
    degree: 'B.Tech.',
    name: 'Artificial Intelligence and Data Science',
    shortName: 'AI & DS',
    aliases: ['AIDS', 'AI & DS', 'AI and Data Science', 'B.Tech AIDS', 'B.Tech AI & DS'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Artificial Intelligence and Machine Learning',
    degree: 'B.Tech.',
    name: 'Artificial Intelligence and Machine Learning',
    shortName: 'AI & ML',
    aliases: ['AIML', 'AI & ML', 'AI and Machine Learning', 'B.Tech AIML', 'B.Tech AI & ML'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Computer Science and Business Systems',
    degree: 'B.Tech.',
    name: 'Computer Science and Business Systems',
    shortName: 'CSBS',
    aliases: ['CSBS', 'CS and Business Systems', 'B.Tech CSBS'],
    category: 'engineering',
    group: 'COMPUTER / IT',
    source: 'Anna University',
  },

  // TECHNOLOGY
  {
    displayName: 'B.Tech. Agricultural Engineering',
    degree: 'B.Tech.',
    name: 'Agricultural Engineering',
    shortName: 'AGRI',
    aliases: ['Agri', 'Agricultural', 'B.Tech Agri', 'B.Tech Agricultural Engineering'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Chemical Engineering',
    degree: 'B.Tech.',
    name: 'Chemical Engineering',
    shortName: 'CHEM',
    aliases: ['Chemical', 'Chem Engg', 'B.Tech Chemical Engineering'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Chemical and Electrochemical Engineering',
    degree: 'B.Tech.',
    name: 'Chemical and Electrochemical Engineering',
    shortName: 'ELECTROCHEM',
    aliases: ['Electrochemical', 'B.Tech Chemical and Electrochemical Engineering'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Ceramic Technology',
    degree: 'B.Tech.',
    name: 'Ceramic Technology',
    shortName: 'CERAMIC',
    aliases: ['Ceramic', 'Ceramic Technology', 'B.Tech Ceramic Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Industrial Biotechnology',
    degree: 'B.Tech.',
    name: 'Industrial Biotechnology',
    shortName: 'IND BIOTECH',
    aliases: ['Industrial Biotech', 'B.Tech Industrial Biotechnology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Biotechnology',
    degree: 'B.Tech.',
    name: 'Biotechnology',
    shortName: 'BIOTECH',
    aliases: ['Biotech', 'Bio-Technology', 'B.Tech Biotech', 'B.Tech Biotechnology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Food Technology',
    degree: 'B.Tech.',
    name: 'Food Technology',
    shortName: 'FOOD TECH',
    aliases: ['Food Tech', 'Food Technology', 'B.Tech Food Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Pharmaceutical Technology',
    degree: 'B.Tech.',
    name: 'Pharmaceutical Technology',
    shortName: 'PHARMA TECH',
    aliases: ['Pharma Tech', 'Pharmaceutical', 'B.Tech Pharmaceutical Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Leather Technology',
    degree: 'B.Tech.',
    name: 'Leather Technology',
    shortName: 'LEATHER',
    aliases: ['Leather Tech', 'Leather', 'B.Tech Leather Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Petroleum Engineering',
    degree: 'B.Tech.',
    name: 'Petroleum Engineering',
    shortName: 'PETROLEUM',
    aliases: ['B.Tech. Petroleum Engineering and Technology', 'Petroleum', 'Petroleum Engineering', 'Petroleum Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Petrochemical Technology',
    degree: 'B.Tech.',
    name: 'Petrochemical Technology',
    shortName: 'PETROCHEM',
    aliases: ['Petrochemical', 'Petrochemical Technology', 'B.Tech Petrochemical Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.E. Petrochemical Engineering',
    degree: 'B.E.',
    name: 'Petrochemical Engineering',
    shortName: 'PETROCHEM ENG',
    aliases: ['Petrochemical Engg', 'B.E Petrochemical Engineering'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Plastics Technology',
    degree: 'B.Tech.',
    name: 'Plastics Technology',
    shortName: 'PLASTICS',
    aliases: ['B.Tech. Plastic Technology', 'Plastic Technology', 'Plastics Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Polymer Technology',
    degree: 'B.Tech.',
    name: 'Polymer Technology',
    shortName: 'POLYMER',
    aliases: ['Polymer', 'Polymer Technology', 'B.Tech Polymer Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Rubber and Plastics Technology',
    degree: 'B.Tech.',
    name: 'Rubber and Plastics Technology',
    shortName: 'RUBBER & PLASTICS',
    aliases: ['Rubber Technology', 'Rubber and Plastics', 'B.Tech Rubber and Plastics Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Textile Technology',
    degree: 'B.Tech.',
    name: 'Textile Technology',
    shortName: 'TEXTILE',
    aliases: ['Textile', 'Textile Technology', 'B.Tech Textile Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Textile Chemistry',
    degree: 'B.Tech.',
    name: 'Textile Chemistry',
    shortName: 'TEXTILE CHEM',
    aliases: ['Textile Chemistry', 'B.Tech Textile Chemistry'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Fashion Technology',
    degree: 'B.Tech.',
    name: 'Fashion Technology',
    shortName: 'FASHION TECH',
    aliases: ['Fashion Tech', 'Fashion Technology', 'B.Tech Fashion Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Apparel Technology',
    degree: 'B.Tech.',
    name: 'Apparel Technology',
    shortName: 'APPAREL TECH',
    aliases: ['Apparel Tech', 'Apparel Technology', 'B.Tech Apparel Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },
  {
    displayName: 'B.Tech. Handloom and Textile Technology',
    degree: 'B.Tech.',
    name: 'Handloom and Textile Technology',
    shortName: 'HANDLOOM',
    aliases: ['Handloom', 'Handloom Technology', 'B.Tech Handloom and Textile Technology'],
    category: 'engineering',
    group: 'TECHNOLOGY',
    source: 'Anna University',
  },

  // ── 4. ARTS — B.A. / HUMANITIES ──
  {
    displayName: 'B.A. Tamil Literature',
    degree: 'B.A.',
    name: 'Tamil Literature',
    shortName: 'BA Tamil Lit',
    aliases: ['B.A. Tamil', 'Tamil', 'Tamil Literature', 'BA Tamil'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Tamil (Creative Writing)',
    degree: 'B.A.',
    name: 'Tamil',
    specialization: 'Creative Writing',
    shortName: 'BA Tamil CW',
    aliases: ['Tamil Creative Writing', 'BA Tamil Creative Writing'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Applied Tamil',
    degree: 'B.A.',
    name: 'Applied Tamil',
    shortName: 'BA Applied Tamil',
    aliases: ['Applied Tamil'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. English Literature',
    degree: 'B.A.',
    name: 'English Literature',
    shortName: 'BA English Lit',
    aliases: ['B.A. English', 'English', 'English Literature', 'BA English'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. English Literature with Computer Applications',
    degree: 'B.A.',
    name: 'English Literature',
    specialization: 'Computer Applications',
    shortName: 'BA English (CA)',
    aliases: ['English CA', 'English with Computer Applications'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. History',
    degree: 'B.A.',
    name: 'History',
    shortName: 'BA History',
    aliases: ['History', 'BA History'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Sociology',
    degree: 'B.A.',
    name: 'Sociology',
    shortName: 'BA Sociology',
    aliases: ['Sociology', 'BA Sociology'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Economics',
    degree: 'B.A.',
    name: 'Economics',
    shortName: 'BA Economics',
    aliases: ['Economics', 'BA Economics'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Political Science',
    degree: 'B.A.',
    name: 'Political Science',
    shortName: 'BA Pol Science',
    aliases: ['Political Science', 'Pol Science', 'BA Political Science'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Public Administration',
    degree: 'B.A.',
    name: 'Public Administration',
    shortName: 'BA Public Admin',
    aliases: ['Public Administration', 'Public Admin', 'BA Public Administration'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Tourism and Travel Management',
    degree: 'B.A.',
    name: 'Tourism and Travel Management',
    shortName: 'BA Tourism',
    aliases: ['Tourism', 'Travel Management', 'Tourism and Travel Management'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Economics with Computer Applications',
    degree: 'B.A.',
    name: 'Economics',
    specialization: 'Computer Applications',
    shortName: 'BA Econ (CA)',
    aliases: ['Economics CA', 'Economics with CA'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Economics with Banking and Insurance',
    degree: 'B.A.',
    name: 'Economics',
    specialization: 'Banking and Insurance',
    shortName: 'BA Econ (BI)',
    aliases: ['Economics Banking and Insurance'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Carnatic Music',
    degree: 'B.A.',
    name: 'Carnatic Music',
    shortName: 'BA Music',
    aliases: ['Carnatic Music', 'Music'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Defence Studies',
    degree: 'B.A.',
    name: 'Defence Studies',
    shortName: 'BA Defence',
    aliases: ['B.A. Defence and Strategic Studies', 'Defence', 'Defence Studies', 'Strategic Studies'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Economics with Logistics and Freight Management',
    degree: 'B.A.',
    name: 'Economics',
    specialization: 'Logistics and Freight Management',
    shortName: 'BA Econ (Logistics)',
    aliases: ['Economics Logistics', 'Economics Freight Management'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Performing Arts',
    degree: 'B.A.',
    name: 'Performing Arts',
    shortName: 'BA Performing Arts',
    aliases: ['Performing Arts', 'Drama', 'Dance'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Criminology',
    degree: 'B.A.',
    name: 'Criminology',
    shortName: 'BA Criminology',
    aliases: ['B.A. Criminology and Police Administration', 'Criminology', 'Police Administration'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Journalism and Mass Communication',
    degree: 'B.A.',
    name: 'Journalism and Mass Communication',
    shortName: 'BA Journalism',
    aliases: ['Journalism', 'Mass Communication', 'BA Journalism'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.A. Arabic',
    degree: 'B.A.',
    name: 'Arabic',
    shortName: 'BA Arabic',
    aliases: ['Arabic', 'BA Arabic'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathidasan University',
  },
  {
    displayName: 'B.A. Sanskrit',
    degree: 'B.A.',
    name: 'Sanskrit',
    shortName: 'BA Sanskrit',
    aliases: ['Sanskrit', 'BA Sanskrit'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathidasan University',
  },
  {
    displayName: 'B.A. Afzal-Ul-Ulama',
    degree: 'B.A.',
    name: 'Afzal-Ul-Ulama',
    shortName: 'BA Afzal-Ul-Ulama',
    aliases: ['Afzal-Ul-Ulama', 'Islamic Studies'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathidasan University',
  },
  {
    displayName: 'B.A. Literature',
    degree: 'B.A.',
    name: 'Literature',
    shortName: 'BA Literature',
    aliases: ['Literature', 'BA Literature'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Litt. Tamil',
    degree: 'B.Litt.',
    name: 'Tamil',
    shortName: 'B.Litt',
    aliases: ['B.Litt.', 'B.Litt', 'B.Litt Tamil', 'Bachelor of Literature'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.S.W. Bachelor of Social Work',
    degree: 'B.S.W.',
    name: 'Social Work',
    shortName: 'BSW',
    aliases: ['B.S.W.', 'BSW', 'Bachelor of Social Work', 'Social Work'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.S.W. Pulavar Degree',
    degree: 'B.S.W.',
    name: 'Pulavar Degree',
    shortName: 'BSW Pulavar',
    aliases: ['Pulavar', 'Pulavar Degree'],
    category: 'arts_science',
    group: 'ARTS',
    source: 'Bharathiar University',
  },

  // ── 5. MANAGEMENT — B.B.A. ──
  {
    displayName: 'B.B.A.',
    degree: 'B.B.A.',
    name: 'Business Administration',
    shortName: 'BBA',
    aliases: ['BBA', 'Bachelor of Business Administration'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Aviation Management',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Aviation Management',
    shortName: 'BBA Aviation',
    aliases: ['BBA Aviation', 'Aviation Management'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Banking',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Banking',
    shortName: 'BBA Banking',
    aliases: ['BBA Banking'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Business Process Management',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Business Process Management',
    shortName: 'BBA BPM',
    aliases: ['BBA BPM', 'BPM', 'Business Process Management'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Information Systems',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Information Systems',
    shortName: 'BBA IS',
    aliases: ['BBA Information Systems', 'BBA IS'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. International Business',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'International Business',
    shortName: 'BBA IB',
    aliases: ['BBA IB', 'International Business', 'BBA International Business'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Logistics and Supply Chain Management',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Logistics and Supply Chain Management',
    shortName: 'BBA Logistics',
    aliases: ['B.B.A. Logistics', 'BBA Logistics', 'Logistics', 'Supply Chain Management', 'SCM'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Retail Management',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Retail Management',
    shortName: 'BBA Retail',
    aliases: ['BBA Retail', 'Retail Management'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Computer Applications',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Computer Applications',
    shortName: 'BBA CA',
    aliases: ['BBA CA', 'BBA Computer Applications'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Financial Management',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Financial Management',
    shortName: 'BBA FM',
    aliases: ['BBA Finance', 'Financial Management', 'BBA FM'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.B.A. Investment',
    degree: 'B.B.A.',
    name: 'Business Administration',
    specialization: 'Investment',
    shortName: 'BBA Investment',
    aliases: ['BBA Investment', 'Investment Management'],
    category: 'arts_science',
    group: 'MANAGEMENT',
    source: 'Bharathiar University',
  },

  // ── 6. COMPUTER APPLICATIONS ──
  {
    displayName: 'B.C.A. Bachelor of Computer Applications',
    degree: 'B.C.A.',
    name: 'Computer Applications',
    shortName: 'BCA',
    aliases: ['B.C.A.', 'BCA', 'Bachelor of Computer Applications', 'Computer Applications'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },

  // ── 7. COMMERCE — B.COM. ──
  {
    displayName: 'B.Com.',
    degree: 'B.Com.',
    name: 'Commerce',
    shortName: 'B.Com',
    aliases: ['B.Com', 'BCom', 'Bachelor of Commerce', 'Commerce'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Accounting and Taxation',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Accounting and Taxation',
    shortName: 'B.Com (A&T)',
    aliases: ['BCom Accounting and Taxation', 'Taxation', 'Tax'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Actuarial Management',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Actuarial Management',
    shortName: 'B.Com (Actuarial)',
    aliases: ['Actuarial Management', 'Actuarial'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Applied Business Accounting',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Applied Business Accounting',
    shortName: 'B.Com (ABA)',
    aliases: ['Applied Business Accounting'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Banking and Finance',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Banking and Finance',
    shortName: 'B.Com (BF)',
    aliases: ['B.Com. Banking', 'Banking and Finance', 'Banking', 'BCom Banking'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Banking and Insurance',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Banking and Insurance',
    shortName: 'B.Com (BI)',
    aliases: ['B.Com. Banking and Insurance Management', 'Banking and Insurance', 'Insurance'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Business Administration',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Business Administration',
    shortName: 'B.Com (BA)',
    aliases: ['BCom Business Administration'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Business Analytics',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Business Analytics',
    shortName: 'B.Com (Analytics)',
    aliases: ['Business Analytics', 'BCom Analytics'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Business Process Services',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Business Process Services',
    shortName: 'B.Com (BPS)',
    aliases: ['B.Com. Business Process Systems', 'BPS', 'Business Process Services'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Capital Markets',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Capital Markets',
    shortName: 'B.Com (Capital Markets)',
    aliases: ['Capital Markets'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Co-Operation',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Co-Operation',
    shortName: 'B.Com (Co-Op)',
    aliases: ['B.Com. Co-Operative Management', 'B.Com. with Diploma in Cooperative Management', 'Co-operation', 'Cooperative Management'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Co-Operation with Computer Applications',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Co-Operation with Computer Applications',
    shortName: 'B.Com (Co-Op CA)',
    aliases: ['Cooperation CA', 'Cooperative with CA'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Corporate Secretaryship',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Corporate Secretaryship',
    shortName: 'B.Com (CS)',
    aliases: ['B.Com CS', 'Corporate Secretaryship', 'Corporate'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Corporate Secretaryship with Computer Applications',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Corporate Secretaryship with Computer Applications',
    shortName: 'B.Com (CS CA)',
    aliases: ['Corporate Secretaryship CA', 'CS with CA'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Cost Accounting',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Cost Accounting',
    shortName: 'B.Com (Cost)',
    aliases: ['B.Com. Cost and Management Accounting', 'Cost Accounting', 'CMA'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Digital Marketing and Data Mining',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Digital Marketing and Data Mining',
    shortName: 'B.Com (DM)',
    aliases: ['Digital Marketing', 'Data Mining', 'BCom Digital Marketing'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. E-Commerce',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'E-Commerce',
    shortName: 'B.Com (E-Com)',
    aliases: ['E-Commerce', 'BCom E-Commerce'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Finance',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Finance',
    shortName: 'B.Com (Finance)',
    aliases: ['B.Com. Financial Services', 'B.Com. Financial System', 'Finance', 'Financial Services'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Foreign Trade',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Foreign Trade',
    shortName: 'B.Com (FT)',
    aliases: ['Foreign Trade', 'BCom Foreign Trade'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Goods and Services Tax',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Goods and Services Tax',
    shortName: 'B.Com (GST)',
    aliases: ['GST', 'Goods and Services Tax', 'BCom GST'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. International Business',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'International Business',
    shortName: 'B.Com (IB)',
    aliases: ['B.Com. International Business and Finance', 'International Business', 'BCom IB'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Professional Accounting',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Professional Accounting',
    shortName: 'B.Com (PA)',
    aliases: ['B.Com PA', 'Professional Accounting', 'BCom PA', 'BCom Professional Accounting'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Retail Marketing',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Retail Marketing',
    shortName: 'B.Com (Retail)',
    aliases: ['Retail Marketing', 'BCom Retail'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Accounting and Finance',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Accounting and Finance',
    shortName: 'B.Com (A&F)',
    aliases: ['B.Com AF', 'Accounting and Finance', 'BCom Accounting and Finance'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Computer Applications',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Computer Applications',
    shortName: 'B.Com (CA)',
    aliases: ['B.Com CA', 'BCom CA', 'Commerce with Computer Applications'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Information Technology',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Information Technology',
    shortName: 'B.Com (IT)',
    aliases: ['B.Com IT', 'BCom IT', 'Commerce with IT'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Applied',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Applied',
    shortName: 'B.Com (Applied)',
    aliases: ['Applied Commerce'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Com. Bank Management',
    degree: 'B.Com.',
    name: 'Commerce',
    specialization: 'Bank Management',
    shortName: 'B.Com (Bank Mgmt)',
    aliases: ['Bank Management'],
    category: 'arts_science',
    group: 'COMMERCE',
    source: 'Bharathiar University',
  },

  // ── 8. SCIENCE — COMPUTER / DIGITAL ──
  {
    displayName: 'B.Sc. Computer Science',
    degree: 'B.Sc.',
    name: 'Computer Science',
    shortName: 'B.Sc CS',
    aliases: ['B.Sc CS', 'BSc CS', 'BSc Computer Science', 'Computer Science'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (Graphic and Creative Design)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Graphic and Creative Design',
    shortName: 'B.Sc CS (Graphics)',
    aliases: ['Graphic and Creative Design', 'Graphic Design'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (Data Science)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Data Science',
    shortName: 'B.Sc CS (DS)',
    aliases: ['B.Sc Data Science', 'B.Sc. Data Science and Analytics', 'Data Science', 'Data Analytics', 'B.Sc. Computer Science with Data Analytics'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (Artificial Intelligence)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Artificial Intelligence',
    shortName: 'B.Sc CS (AI)',
    aliases: ['B.Sc AI', 'Artificial Intelligence', 'B.Sc. Artificial Intelligence and Data Science', 'B.Sc. Artificial Intelligence and Machine Learning'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science with Cognitive Systems',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Cognitive Systems',
    shortName: 'B.Sc CS (Cognitive)',
    aliases: ['Cognitive Systems', 'CS Cognitive Systems'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science with Cyber Security',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Cyber Security',
    shortName: 'B.Sc CS (Cyber)',
    aliases: ['B.Sc. Cyber Security', 'Cyber Security', 'Cyber', 'B.Sc Cyber Security'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science and Applications',
    degree: 'B.Sc.',
    name: 'Computer Science and Applications',
    shortName: 'B.Sc CSA',
    aliases: ['Computer Science and Applications'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Technology',
    degree: 'B.Sc.',
    name: 'Computer Technology',
    shortName: 'B.Sc CT',
    aliases: ['Computer Technology', 'BSc CT'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (DevOps and Cloud)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'DevOps and Cloud',
    shortName: 'B.Sc CS (Cloud)',
    aliases: ['DevOps', 'Cloud', 'DevOps and Cloud'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (Data Science and Visualization)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Data Science and Visualization',
    shortName: 'B.Sc CS (Vis)',
    aliases: ['Data Visualization', 'Data Science and Visualization'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Computer Science (Full Stack Web Development)',
    degree: 'B.Sc.',
    name: 'Computer Science',
    specialization: 'Full Stack Web Development',
    shortName: 'B.Sc CS (Full Stack)',
    aliases: ['Full Stack', 'Web Development', 'Full Stack Web Development'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Digital and Cyber Forensic Science',
    degree: 'B.Sc.',
    name: 'Digital and Cyber Forensic Science',
    shortName: 'B.Sc Cyber Forensic',
    aliases: ['Digital Forensics', 'Cyber Forensics', 'Forensic Science'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Information Technology',
    degree: 'B.Sc.',
    name: 'Information Technology',
    shortName: 'B.Sc IT',
    aliases: ['B.Sc IT', 'BSc IT', 'Information Technology'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Internet of Things',
    degree: 'B.Sc.',
    name: 'Internet of Things',
    shortName: 'B.Sc IoT',
    aliases: ['B.Sc IoT', 'BSc IoT', 'IoT', 'Internet of Things'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Software Systems',
    degree: 'B.Sc.',
    name: 'Software Systems',
    shortName: 'B.Sc SS',
    aliases: ['Software Systems', 'BSc SS'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Hardware System and Networking',
    degree: 'B.Sc.',
    name: 'Hardware System and Networking',
    shortName: 'B.Sc Hardware',
    aliases: ['Hardware and Networking', 'Networking'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Information Systems Management',
    degree: 'B.Sc.',
    name: 'Information Systems Management',
    shortName: 'B.Sc ISM',
    aliases: ['ISM', 'Information Systems Management'],
    category: 'arts_science',
    group: 'COMPUTER / IT',
    source: 'Bharathiar University',
  },

  // ── 9. SCIENCE — BASIC SCIENCES ──
  {
    displayName: 'B.Sc. Mathematics',
    degree: 'B.Sc.',
    name: 'Mathematics',
    shortName: 'B.Sc Maths',
    aliases: ['Mathematics', 'Maths', 'BSc Maths'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Mathematics with Computer Applications',
    degree: 'B.Sc.',
    name: 'Mathematics',
    specialization: 'Computer Applications',
    shortName: 'B.Sc Maths (CA)',
    aliases: ['Maths CA', 'Mathematics with CA'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Physics',
    degree: 'B.Sc.',
    name: 'Physics',
    shortName: 'B.Sc Physics',
    aliases: ['Physics', 'BSc Physics'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Physics with Computer Applications',
    degree: 'B.Sc.',
    name: 'Physics',
    specialization: 'Computer Applications',
    shortName: 'B.Sc Physics (CA)',
    aliases: ['Physics CA', 'Physics with CA'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Chemistry',
    degree: 'B.Sc.',
    name: 'Chemistry',
    shortName: 'B.Sc Chemistry',
    aliases: ['Chemistry', 'BSc Chemistry'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Statistics',
    degree: 'B.Sc.',
    name: 'Statistics',
    shortName: 'B.Sc Stats',
    aliases: ['Statistics', 'Stats', 'BSc Stats'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Botany',
    degree: 'B.Sc.',
    name: 'Botany',
    shortName: 'B.Sc Botany',
    aliases: ['Botany', 'Plant Science', 'BSc Botany'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Zoology',
    degree: 'B.Sc.',
    name: 'Zoology',
    shortName: 'B.Sc Zoology',
    aliases: ['Zoology', 'Animal Science', 'BSc Zoology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Geography',
    degree: 'B.Sc.',
    name: 'Geography',
    shortName: 'B.Sc Geography',
    aliases: ['Geography', 'BSc Geography'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Geology',
    degree: 'B.Sc.',
    name: 'Geology',
    shortName: 'B.Sc Geology',
    aliases: ['Geology', 'Earth Science', 'BSc Geology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Environmental Science',
    degree: 'B.Sc.',
    name: 'Environmental Science',
    shortName: 'B.Sc Env Science',
    aliases: ['Environmental Science', 'BSc Environmental Science'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Renewable Energy',
    degree: 'B.Sc.',
    name: 'Renewable Energy',
    shortName: 'B.Sc Energy',
    aliases: ['Renewable Energy', 'Solar Energy'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Wild Life Biology',
    degree: 'B.Sc.',
    name: 'Wild Life Biology',
    shortName: 'B.Sc Wildlife',
    aliases: ['Wildlife Biology', 'Wildlife'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },

  // ── 10. SCIENCE — LIFE SCIENCES ──
  {
    displayName: 'B.Sc. Agri Biology',
    degree: 'B.Sc.',
    name: 'Agri Biology',
    shortName: 'B.Sc Agri Bio',
    aliases: ['Agri Biology', 'Agricultural Biology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Biochemistry',
    degree: 'B.Sc.',
    name: 'Biochemistry',
    shortName: 'B.Sc Biochem',
    aliases: ['B.Sc. Biochemistry with Nanotechnology', 'Biochemistry', 'BSc Biochem'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Biotechnology',
    degree: 'B.Sc.',
    name: 'Biotechnology',
    shortName: 'B.Sc Biotech',
    aliases: ['Biotechnology', 'Biotech', 'BSc Biotech'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Microbiology',
    degree: 'B.Sc.',
    name: 'Microbiology',
    shortName: 'B.Sc Micro',
    aliases: ['B.Sc. Microbiology with Nanotechnology', 'Microbiology', 'BSc Microbiology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Plant Biology and Biotechnology',
    degree: 'B.Sc.',
    name: 'Plant Biology and Biotechnology',
    shortName: 'B.Sc Plant Biotech',
    aliases: ['Plant Biology', 'Plant Biotechnology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Food Processing Technology and Management',
    degree: 'B.Sc.',
    name: 'Food Processing Technology and Management',
    shortName: 'B.Sc Food Proc',
    aliases: ['Food Processing', 'Food Technology and Management'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Food Sciences and Nutrition',
    degree: 'B.Sc.',
    name: 'Food Sciences and Nutrition',
    shortName: 'B.Sc Food & Nut',
    aliases: ['Food Science', 'Food Sciences and Nutrition'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Nutrition and Dietetics',
    degree: 'B.Sc.',
    name: 'Nutrition and Dietetics',
    shortName: 'B.Sc Nut & Diet',
    aliases: ['B.Sc. Nutrition Food Service Management and Dietetics', 'Nutrition', 'Dietetics'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Home Science',
    degree: 'B.Sc.',
    name: 'Home Science',
    shortName: 'B.Sc Home Science',
    aliases: ['B.Sc. Home Science - Nutrition and Dietetics', 'Home Science'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Psychology',
    degree: 'B.Sc.',
    name: 'Psychology',
    shortName: 'B.Sc Psychology',
    aliases: ['Psychology', 'BSc Psychology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },

  // ── 11. SCIENCE — ELECTRONICS ──
  {
    displayName: 'B.Sc. Electronics',
    degree: 'B.Sc.',
    name: 'Electronics',
    shortName: 'B.Sc Electronics',
    aliases: ['B.Sc. Electronics and Communication Systems', 'Electronics', 'ECS'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },

  // ── 12. SCIENCE — MEDIA / DESIGN / FASHION ──
  {
    displayName: 'B.Sc. Animation and Visual Effects',
    degree: 'B.Sc.',
    name: 'Animation and Visual Effects',
    shortName: 'B.Sc Animation',
    aliases: ['Animation', 'VFX', 'Visual Effects'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Costume Design and Fashion',
    degree: 'B.Sc.',
    name: 'Costume Design and Fashion',
    shortName: 'B.Sc Fashion',
    aliases: [
      'B.Sc. Apparel Fashion Designing',
      'B.Sc. Apparel Manufacturing and Merchandising',
      'B.Sc. Apparel Production Technology',
      'B.Sc. Fashion Apparel Management',
      'B.Sc. Fashion Technology and Costume Designing',
      'B.Sc. Garment Design and Production',
      'B.Sc. Apparel and Fashion Technology',
      'Fashion Designing',
      'Costume Design',
    ],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Interior Design',
    degree: 'B.Sc.',
    name: 'Interior Design',
    shortName: 'B.Sc Interior Design',
    aliases: ['B.Sc. Interior Design with Computer Applications', 'Interior Design'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Multimedia and Web Technology',
    degree: 'B.Sc.',
    name: 'Multimedia and Web Technology',
    shortName: 'B.Sc Multimedia',
    aliases: ['Multimedia', 'Web Technology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Visual Communication',
    degree: 'B.Sc.',
    name: 'Visual Communication',
    shortName: 'B.Sc Viscom',
    aliases: ['B.Sc. Visual Communication (Electronic Media)', 'Viscom', 'Visual Communication'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Beauty and Wellness',
    degree: 'B.Sc.',
    name: 'Beauty and Wellness',
    shortName: 'B.Sc Wellness',
    aliases: ['Beauty and Wellness', 'Cosmetology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },

  // ── 13. SCIENCE — HOSPITALITY / PROFESSIONAL ──
  {
    displayName: 'B.Sc. Catering Science and Hotel Management',
    degree: 'B.Sc.',
    name: 'Catering Science and Hotel Management',
    shortName: 'B.Sc Catering',
    aliases: ['B.Sc. Hotel Management and Catering Science', 'Catering Science', 'Hotel Management'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Clinical Laboratory Technology',
    degree: 'B.Sc.',
    name: 'Clinical Laboratory Technology',
    shortName: 'B.Sc CLT',
    aliases: ['CLT', 'Clinical Lab', 'Medical Laboratory Technology'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Hospitality and Airline Catering Management',
    degree: 'B.Sc.',
    name: 'Hospitality and Airline Catering Management',
    shortName: 'B.Sc Airline Catering',
    aliases: ['B.Sc. Hospitality and Tourism Management', 'Airline Catering', 'Hospitality Management'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Hospital Administration',
    degree: 'B.Sc.',
    name: 'Hospital Administration',
    shortName: 'B.Sc Hospital Admin',
    aliases: ['Hospital Administration', 'Hospital Management'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Aviation',
    degree: 'B.Sc.',
    name: 'Aviation',
    shortName: 'B.Sc Aviation',
    aliases: ['Aviation', 'BSc Aviation'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Forensic Science',
    degree: 'B.Sc.',
    name: 'Forensic Science',
    shortName: 'B.Sc Forensic',
    aliases: ['Forensic Science', 'Criminology Science'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Sc. Physical Education',
    degree: 'B.Sc.',
    name: 'Physical Education',
    shortName: 'B.Sc Physical Ed',
    aliases: ['B.Sc. Physical Education, Health Education and Sports', 'Physical Education', 'Sports Science'],
    category: 'arts_science',
    group: 'SCIENCE',
    source: 'Bharathiar University',
  },

  // ── 14. LIBRARY / VOCATIONAL PROGRAMMES ──
  {
    displayName: 'B.Lib.I.Sc. Bachelor of Library and Information Science',
    degree: 'B.Lib.I.Sc.',
    name: 'Library and Information Science',
    shortName: 'B.Lib.I.Sc',
    aliases: ['B.Lib.I.Sc.', 'BLISc', 'Library Science', 'Bachelor of Library and Information Science'],
    category: 'arts_science',
    group: 'VOCATIONAL & OTHERS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Voc. Multimedia and Animation',
    degree: 'B.Voc.',
    name: 'Multimedia and Animation',
    shortName: 'B.Voc Animation',
    aliases: ['B.Voc Animation', 'Multimedia and Animation'],
    category: 'arts_science',
    group: 'VOCATIONAL & OTHERS',
    source: 'Bharathiar University',
  },
  {
    displayName: 'B.Voc. Business Process and Data Analytics',
    degree: 'B.Voc.',
    name: 'Business Process and Data Analytics',
    shortName: 'B.Voc Analytics',
    aliases: ['B.Voc Analytics', 'Business Process and Data Analytics'],
    category: 'arts_science',
    group: 'VOCATIONAL & OTHERS',
    source: 'Bharathiar University',
  },

  // ── 15. PHYSICAL EDUCATION ──
  {
    displayName: 'B.P.Ed. Bachelor of Physical Education',
    degree: 'B.P.Ed.',
    name: 'Physical Education',
    shortName: 'B.P.Ed',
    aliases: ['B.P.Ed.', 'BPEd', 'Bachelor of Physical Education'],
    category: 'arts_science',
    group: 'VOCATIONAL & OTHERS',
    source: 'Bharathiar University',
  },
];

console.log('Total Master Program Inputs:', MASTER_INPUTS.length);
