import { PROGRAMS } from '../src/data/programs';

export const OFFICIAL_LIST = [
  'B.E. Civil Engineering',
  'B.E. Geo Informatics Engineering',
  'B.E. Geoinformatics Engineering',
  'B.E. Environmental Engineering',
  'B.E. Civil Engineering (Environmental Engineering)',
  'B.E. Environmental Science and Technology',
  'B.Tech. Agricultural Engineering',
  'B.E. Mechanical Engineering',
  'B.E. Materials Science and Engineering',
  'B.E. Mining Engineering',
  'B.E. Printing and Packaging Technology',
  'B.E. Manufacturing Engineering',
  'B.E. Industrial Engineering',
  'B.E. Aeronautical Engineering',
  'B.E. Automobile Engineering',
  'B.E. Production Engineering',
  'B.E. Robotics and Automation Engineering',
  'B.E. Robotics and Automation',
  'B.E. Mechatronics Engineering',
  'B.E. Mechanical and Automation Engineering',
  'B.E. Industrial Engineering and Management',
  'B.E. Marine Engineering',
  'B.E. Aerospace Engineering',
  'B.E. Mechanical Engineering (Specialized in Automobile)',
  'B.E. Mechanical Engineering (Specialized in Smart Manufacturing)',
  'B.E. Electrical and Electronics Engineering',
  'B.E. Electrical and Computer Engineering',
  'B.E. Electronics and Instrumentation Engineering',
  'B.E. Instrumentation and Control Engineering',
  'B.E. Electrical and Electronics Engineering (Training Integrated Programme)',
  'B.E. Electronics and Communication Engineering',
  'B.E. Biomedical Engineering',
  'B.E. Medical Electronics',
  'B.E. Electronics and Computer Engineering',
  'B.E. Electronics and Telecommunication Engineering',
  'B.Tech. Electronics Engineering (VLSI Design and Technology)',
  'B.E. Computer Science and Engineering',
  'B.E. Computer and Communication Engineering',
  'B.E. Computer Science and Engineering (Data Science)',
  'B.E. Computer Science and Engineering (Cyber Security)',
  'B.E. Computer Science and Engineering (Internet of Things)',
  'B.E. Computer Science and Engineering (Artificial Intelligence)',
  'B.E. Computer Science and Engineering (Artificial Intelligence and Machine Learning)',
  'B.E. Computer Science and Design',
  'B.Tech. Information Technology',
  'B.Tech. Artificial Intelligence and Data Science',
  'B.Tech. Artificial Intelligence and Machine Learning',
  'B.Tech. Computer Science and Business Systems',
  'B.Tech. Chemical Engineering',
  'B.Tech. Chemical and Electrochemical Engineering',
  'B.Tech. Ceramic Technology',
  'B.Tech. Industrial Biotechnology',
  'B.Tech. Biotechnology',
  'B.Tech. Food Technology',
  'B.Tech. Pharmaceutical Technology',
  'B.Tech. Leather Technology',
  'B.Tech. Petroleum Engineering',
  'B.Tech. Petroleum Engineering and Technology',
  'B.Tech. Petrochemical Technology',
  'B.E. Petrochemical Engineering',
  'B.Tech. Plastics Technology',
  'B.Tech. Plastic Technology',
  'B.Tech. Polymer Technology',
  'B.Tech. Rubber and Plastics Technology',
  'B.Tech. Textile Technology',
  'B.Tech. Textile Chemistry',
  'B.Tech. Fashion Technology',
  'B.Tech. Apparel Technology',
  'B.Tech. Handloom and Textile Technology',
  'B.Arch.',
  'B.Arch. Architecture',
  'B.Plan.',
  'B.Plan. Bachelor of Planning',
  'B.Des.',
  'B.Des. Bachelor of Design',
  'B.A. Tamil Literature',
  'B.A. Tamil (Creative Writing)',
  'B.A. Tamil',
  'B.A. Applied Tamil',
  'B.A. English Literature',
  'B.A. English Literature with Computer Applications',
  'B.A. English',
  'B.A. History',
  'B.A. Sociology',
  'B.A. Economics',
  'B.A. Political Science',
  'B.A. Public Administration',
  'B.A. Tourism and Travel Management',
  'B.A. Economics with Computer Applications',
  'B.A. Economics with Banking and Insurance',
  'B.A. Carnatic Music',
  'B.A. Defence Studies',
  'B.A. Defence and Strategic Studies',
  'B.A. Economics with Logistics and Freight Management',
  'B.A. Performing Arts',
  'B.A. Criminology',
  'B.A. Criminology and Police Administration',
  'B.A. Journalism and Mass Communication',
  'B.A. Arabic',
  'B.A. Sanskrit',
  'B.A. Afzal-Ul-Ulama',
  'B.A. Literature',
  'B.Litt.',
  'B.Litt. Tamil',
  'B.S.W.',
  'B.S.W. Bachelor of Social Work',
  'B.S.W. Pulavar Degree',
  'B.B.A.',
  'B.B.A. Aviation Management',
  'B.B.A. Banking',
  'B.B.A. Business Process Management',
  'B.B.A. Information Systems',
  'B.B.A. International Business',
  'B.B.A. Logistics',
  'B.B.A. Logistics and Supply Chain Management',
  'B.B.A. Retail Management',
  'B.B.A. Computer Applications',
  'B.B.A. Financial Management',
  'B.B.A. Investment',
  'B.C.A.',
  'B.C.A. Bachelor of Computer Applications',
  'B.Com.',
  'B.Com. Accounting and Taxation',
  'B.Com. Actuarial Management',
  'B.Com. Applied Business Accounting',
  'B.Com. Banking',
  'B.Com. Banking and Finance',
  'B.Com. Banking and Insurance',
  'B.Com. Business Administration',
  'B.Com. Business Analytics',
  'B.Com. Business Process Services',
  'B.Com. Business Process Systems',
  'B.Com. Capital Markets',
  'B.Com. Co-Operation',
  'B.Com. Co-Operation with Computer Applications',
  'B.Com. Corporate Secretaryship',
  'B.Com. Corporate Secretaryship with Computer Applications',
  'B.Com. Cost Accounting',
  'B.Com. Cost and Management Accounting',
  'B.Com. Digital Marketing and Data Mining',
  'B.Com. E-Commerce',
  'B.Com. Finance',
  'B.Com. Financial Services',
  'B.Com. Financial System',
  'B.Com. Foreign Trade',
  'B.Com. Goods and Services Tax',
  'B.Com. International Business',
  'B.Com. International Business and Finance',
  'B.Com. Professional Accounting',
  'B.Com. Retail Marketing',
  'B.Com. Accounting and Finance',
  'B.Com. Computer Applications',
  'B.Com. Information Technology',
  'B.Com. Applied',
  'B.Com. Bank Management',
  'B.Com. Banking and Insurance Management',
  'B.Com. Co-Operative Management',
  'B.Com. with Diploma in Cooperative Management',
  'B.Sc. Computer Science',
  'B.Sc. Computer Science (Graphic and Creative Design)',
  'B.Sc. Computer Science (Data Science)',
  'B.Sc. Computer Science (Artificial Intelligence)',
  'B.Sc. Computer Science (Artificial Intelligence and Data Science)',
  'B.Sc. Computer Science with Cognitive Systems',
  'B.Sc. Computer Science with Cyber Security',
  'B.Sc. Computer Science and Applications',
  'B.Sc. Computer Science with Data Analytics',
  'B.Sc. Computer Technology',
  'B.Sc. Computer Science (DevOps and Cloud)',
  'B.Sc. Computer Science (Data Science and Visualization)',
  'B.Sc. Computer Science (Full Stack Web Development)',
  'B.Sc. Artificial Intelligence and Machine Learning',
  'B.Sc. Artificial Intelligence and Data Science',
  'B.Sc. Data Science',
  'B.Sc. Data Science and Analytics',
  'B.Sc. Digital and Cyber Forensic Science',
  'B.Sc. Cyber Security',
  'B.Sc. Information Technology',
  'B.Sc. Internet of Things',
  'B.Sc. Software Systems',
  'B.Sc. Hardware System and Networking',
  'B.Sc. Information Systems Management',
  'B.Sc. Mathematics',
  'B.Sc. Mathematics with Computer Applications',
  'B.Sc. Physics',
  'B.Sc. Physics with Computer Applications',
  'B.Sc. Chemistry',
  'B.Sc. Statistics',
  'B.Sc. Botany',
  'B.Sc. Zoology',
  'B.Sc. Geography',
  'B.Sc. Geology',
  'B.Sc. Environmental Science',
  'B.Sc. Renewable Energy',
  'B.Sc. Wild Life Biology',
  'B.Sc. Agri Biology',
  'B.Sc. Biochemistry',
  'B.Sc. Biochemistry with Nanotechnology',
  'B.Sc. Biotechnology',
  'B.Sc. Microbiology',
  'B.Sc. Microbiology with Nanotechnology',
  'B.Sc. Plant Biology and Biotechnology',
  'B.Sc. Food Processing Technology and Management',
  'B.Sc. Food Sciences and Nutrition',
  'B.Sc. Nutrition and Dietetics',
  'B.Sc. Nutrition Food Service Management and Dietetics',
  'B.Sc. Home Science',
  'B.Sc. Home Science - Nutrition and Dietetics',
  'B.Sc. Psychology',
  'B.Sc. Electronics',
  'B.Sc. Electronics and Communication Systems',
  'B.Sc. Animation and Visual Effects',
  'B.Sc. Apparel Fashion Designing',
  'B.Sc. Apparel Manufacturing and Merchandising',
  'B.Sc. Apparel Production Technology',
  'B.Sc. Costume Design and Fashion',
  'B.Sc. Fashion Apparel Management',
  'B.Sc. Fashion Technology and Costume Designing',
  'B.Sc. Garment Design and Production',
  'B.Sc. Interior Design',
  'B.Sc. Interior Design with Computer Applications',
  'B.Sc. Multimedia and Web Technology',
  'B.Sc. Visual Communication',
  'B.Sc. Visual Communication (Electronic Media)',
  'B.Sc. Beauty and Wellness',
  'B.Sc. Apparel and Fashion Technology',
  'B.Sc. Catering Science and Hotel Management',
  'B.Sc. Clinical Laboratory Technology',
  'B.Sc. Hospitality and Airline Catering Management',
  'B.Sc. Hospitality and Tourism Management',
  'B.Sc. Hotel Management and Catering Science',
  'B.Sc. Hospital Administration',
  'B.Sc. Aviation',
  'B.Sc. Forensic Science',
  'B.Sc. Physical Education',
  'B.Sc. Physical Education, Health Education and Sports',
  'B.Lib.I.Sc.',
  'B.Lib.I.Sc. Bachelor of Library and Information Science',
  'B.Voc. Multimedia and Animation',
  'B.Voc. Business Process and Data Analytics',
  'B.P.Ed.',
  'B.P.Ed. Bachelor of Physical Education'
];

console.log('Total in list:', OFFICIAL_LIST.length);
const missing = OFFICIAL_LIST.filter(item => !PROGRAMS.some(p => p.displayName.toLowerCase() === item.toLowerCase()));
console.log('Missing items count:', missing.length);
if (missing.length > 0) {
  console.log('Missing items:', missing);
}
