const fs = require('fs');
const path = require('path');

const rawDirectory = [
  {
    district: 'Chennai',
    engineering: [
      'University Departments of Anna University – CEG Campus (College of Engineering, Guindy)',
      'University Departments of Anna University – ACT Campus',
      'University Departments of Anna University – MIT Campus (Madras Institute of Technology)',
      'Meenakshi Sundararajan Engineering College',
      'Loyola-ICAM College of Engineering and Technology',
      'Jeppiaar Engineering College',
      'Jerusalem College of Engineering',
      'Easwari Engineering College',
      'Meenakshi College of Engineering',
      'K.C.G. College of Technology',
      "St. Joseph's College of Engineering",
      'Thangavelu Engineering College',
      'Sri Sairam Institute of Technology',
      'Sri Sairam Engineering College',
      'Tagore Engineering College',
      'Loyola Institute of Technology',
      'Vel Tech',
      'Panimalar Engineering College',
      'Panimalar Institute of Technology',
      'Velammal Engineering College',
      'SA Engineering College',
      'Chennai Institute of Technology',
      'Rajalakshmi Institute of Technology',
      'Madha Engineering College',
      'Madha Institute of Engineering and Technology',
      'Prince Shri Venkateshwara Padmavathy Engineering College',
      'Meenakshi Engineering College',
    ],
    arts_science: [
      'Presidency College (Autonomous)',
      "Queen Mary's College (Autonomous)",
      "Bharathi Women's College (Autonomous)",
      'Government Arts College (Autonomous), Nandanam',
      'Dr. Ambedkar Government Arts College (Autonomous)',
      'Government Arts and Science College, R.K. Nagar',
      'Government Arts and Science College, Thiruvottiyur',
      'Government Arts and Science College, Alandur',
      'Quaid-E-Millath Government College for Women (Autonomous)',
    ],
  },
  {
    district: 'Coimbatore',
    engineering: [
      'Government College of Technology',
      'P.S.G. College of Technology',
      'Coimbatore Institute of Technology',
      'Rathinam Technical Campus',
      'Sri Ranganathar Institute of Engineering and Technology',
      'Pollachi Institute of Engineering and Technology',
      'V.S.B. College of Engineering Technical Campus',
      'Nightingale Institute of Technology',
      'Suguna College of Engineering',
      'Adhiyamaan College of Engineering',
      'Christ The King Engineering College',
      'Sree Sakthi Engineering College',
      'Coimbatore Institute of Engineering and Information Technology',
      'Dr. Mahalingam College of Engineering and Technology',
      'Hindusthan College of Engineering and Technology',
      'Karpagam College of Engineering',
      'Kumaraguru College of Technology',
      'Park College of Engineering Technology',
      'Sri Krishna College of Engineering and Technology',
      'Sri Ramakrishna Engineering College',
      'Tamilnadu College of Engineering',
      'V.L.B. Janakiammal College of Engineering and Technology',
      'Maharaja Prithvi Engineering College',
      'Sri Ramakrishna Institute of Technology',
      'SNS College of Technology',
      'Sri Shakthi Institute of Engineering and Technology',
      'Nehru Institute of Engineering and Technology',
      'Maharaja Institute of Technology',
      'RVS College of Engineering and Technology',
      'Info Institute of Engineering',
      'SNS College of Engineering',
      'Karpagam Institute of Technology',
      'Dr. N.G.P. Institute of Technology',
      'Ranganathan Engineering College',
      'Sri Eashwar Engineering College',
      'Hindustan Institute of Technology',
      'P.A. College of Engineering',
      'SSK College of Engineering and Technology',
      'Adithya Institute of Technology',
      'Kathir College of Engineering',
      'KTVR Knowledge Park for Engineering and Technology',
      'Easa College of Engineering and Technology',
      'Kalasignar Karunanidhi Institute of Technology',
      'KGISL Institute of Technology',
      'PPG Institute of Technology',
      'Jawaharlal Institute of Technology',
      'Indus College of Engineering',
      'Tejaa Shakthi Institute of Technology for Women',
      'United Institute of Technology',
      'Jansons Institute of Technology',
      'Akshaya College of Engineering and Technology',
      'K.P.R. Institute of Engineering and Technology',
      'Sriguru Institute of Technology',
      'Park College of Technology',
      'J.C.T. College of Engineering and Technology',
      'Kalaivani College of Technology',
      'Dr. Nalini Institute of Engineering and Technology',
      'C.M.S. College of Engineering and Technology',
      'RVS Technical Campus',
    ],
    arts_science: [
      'Government Arts College (Autonomous), Coimbatore',
      'Government Arts and Science College, Mettupalayam',
      'Government Arts and Science College, Valparai',
      'Government Arts and Science College, Pollachi',
      'Government Arts and Science College, Thondamuthur',
      'Government Arts and Science College for Women, Puliyakulam',
    ],
  },
  {
    district: 'Madurai',
    engineering: [
      'Thiagarajar College of Engineering',
      'C.R. Engineering College',
      'Vaigai College of Engineering',
      'Kamaraj College of Engineering and Technology',
      'P.T.R. College of Engineering and Technology',
      'Raja College of Engineering and Technology',
      'SACS M.A.V.M.M. Engineering College',
      'Vickram College of Engineering',
      'Fatima Michael College of Engineering and Technology',
      'Ultra College of Engineering and Technology for Women',
      'Velammal College of Engineering and Technology',
      'Latha Mathavan Engineering College',
    ],
    arts_science: [
      'Government Arts and Science College, Thirumangalam',
      'Government Arts College, Melur',
    ],
  },
  {
    district: 'Trichy',
    engineering: [
      'University Departments of Anna University – BIT Campus, Tiruchirappalli',
      'Mahalakshmi Engineering College',
      'Dhanalakshmi Srinivasan Institute of Technology',
      'Sureya College of Engineering',
      'K. Ramakrishnan College of Technology',
      'OAS Institute of Technology and Management',
      'M.A.M. School of Engineering',
      'TRP Engineering College',
      'Shri Angala Amman College of Engineering and Technology',
      'J.J. College of Engineering and Technology',
      'Jayaram College of Engineering and Technology',
      'Kurinji College of Engineering and Technology',
      'MAM College of Engineering',
      'M.I.E.T. Engineering College',
      'Oxford Engineering College',
      'Pavendar Bharathidasan College of Engineering and Technology',
      'Saranathan College of Engineering',
      'Trichy Engineering College',
      'Kongunadu College of Engineering and Technology',
      'Cauvery College of Engineering and Technology',
      'M.A.M. College of Engineering and Technology',
      'K. Ramakrishnan College of Engineering',
      'Indra Ganesan College of Engineering',
      'C.A.R.E. School of Engineering',
      'Shivani Engineering College',
      'Imayam College of Engineering',
      'Vetri Vinayaha College of Engineering and Technology',
      'Shivani Institute of Technology',
    ],
    arts_science: [
      'Government Arts College, Trichy',
      'Government Arts and Science College, Manapparai',
      'Government Arts and Science College, Lalgudi',
    ],
  },
  {
    district: 'Salem',
    engineering: [
      'Sri Shanmugha College of Engineering and Technology',
      'Ganesh College of Engineering',
      'Dhirajlal Gandhi College of Technology',
      'Shree Sathyam College of Engineering and Technology',
      'Government College of Engineering, Salem',
      'SONA College of Technology',
      'Maha College of Engineering',
      'The Kavery Engineering College',
      'AVS Engineering College',
      "Narasu's Sarathy Institute of Technology",
      'Bharathiyar Institute of Engineering for Women',
      'Greentech College of Engineering for Women',
      'Rabindranath Tagore College of Engineering for Women',
      'Tagore Institute of Engineering and Technology',
      'Annapoorana Engineering College',
      'Knowledge Institute of Technology',
      "VSA Educational and Charitable Trust's Group of Institutions",
      'Salem College of Engineering and Technology',
      'S.R.S. College of Engineering and Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Mettur',
      'Government Arts and Science College, Idappadi',
      'Arignar Anna Government Arts College, Athur',
    ],
  },
  {
    district: 'Erode',
    engineering: [
      'Aishwarya College of Engineering and Technology',
      'Vidhya Mandhir Institute of Technology',
      'Bannari Amman Institute of Technology',
      'Erode Sengunthar Engineering College',
      'Institute of Road and Transport Technology',
      'Kongu Engineering College',
      'M.P. Nachimuthu M. Jaganathan Engineering College',
      'Nandha Engineering College',
      'Vellalar College of Engineering and Technology',
      'Maharaja Engineering College for Women',
      'Shree Venkateswara Hi-Tech Engineering College',
      'Surya Engineering College',
      'Nandha Institute of Technology',
      'Sri Ramanathan Engineering College',
      'JKK Muniraja Institute of Technology',
      'Al-Ameen Engineering College',
    ],
    arts_science: [
      'Government Arts and Science College, Sathyamangalam',
      'Government Arts and Science College, Thaalavadi',
      'Government Arts and Science College, Anthiyur',
      'Government Arts and Science College, Modakurichi',
      'Government Arts and Science College, Thittamalai',
    ],
  },
  {
    district: 'Tiruppur',
    engineering: [
      'Jairupaa College of Engineering',
      'Jai Sriram College of Technology',
      'Sasurie College of Engineering',
      'Angel College of Engineering and Technology',
      "Erode Builder Educational Trust's Group of Institutions",
      "Professional Educational Trust's Group of Institutions",
    ],
    arts_science: [
      'Government Arts and Science College, Kangeyam',
      'Government Arts and Science College, Dharapuram',
      'Government Arts and Science College, Avinashi',
      'Government Arts College, Udumalpet',
    ],
  },
  {
    district: 'Namakkal',
    engineering: [
      'Muthayammal Technical Campus',
      'K.S.R. Institute for Engineering and Technology',
      'Annai Mathammal Sheela Engineering College',
      'K.S. Rangaswamy College of Technology',
      'Mahendra Engineering College',
      'Muthayammal Engineering College',
      'Paavai Engineering College',
      'P.G.P. College of Engineering and Technology',
      'K.S.R. College of Engineering',
      'S.S.M. College of Engineering',
      'Sengunthar Engineering College',
      'Vivekanandha College of Engineering for Women',
      'Paavai Group of Institutions',
      'Gnanamani College of Technology',
      'Vivekanandha Institute of Engineering and Technology for Women',
      'Selvam College of Technology',
      'Paavai College of Engineering',
      'Sengunthar College of Engineering for Women',
      'King College of Technology',
      'Mahendra Institute of Technology',
      'Vidhya Vikkas College of Engineering and Technology',
      'Excel Engineering College',
      'CMS College of Engineering',
      'Excel College of Engineering for Women',
      'Mahendra Engineering College for Women',
      'J.K.K. Nataraja College of Engineering and Technology',
      'Pavai College of Technology',
      'Gnanamani College of Engineering',
      "Dr. Nagarathinam's College of Engineering",
      'Excel College of Engineering and Technology',
      'Mahendra Institute of Engineering and Technology',
      'SRG Engineering College',
    ],
    arts_science: [
      'Arignar Anna Government Arts College, Namakkal',
      'Government Arts and Science College, Komarapalayam',
    ],
  },
  {
    district: 'Thanjavur',
    engineering: [
      'SMR East Coast College of Engineering and Technology',
      'K.S.K. College of Engineering and Technology',
      'Star Lion College of Engineering and Technology',
      'P.R. Engineering College',
      'Ponnaiyah Ramajayam College of Engineering and Technology',
      "St. Joseph's College of Engineering and Technology",
      'Parisutham Institute of Science and Technology',
      'Vandayar Engineering College',
      'Annai College of Engineering and Technology',
      'As-Salam College of Engineering and Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Thirukattupalli',
      'Government Arts and Science College, Peravurani',
      'Government Arts College for Women, Kumbakonam',
    ],
  },
  {
    district: 'Tirunelveli',
    engineering: [
      'University Departments of Anna University of Technology, Tirunelveli',
      'Thamirabharani Engineering College',
      'Universal College of Engineering and Technology',
      'A.R. College of Engineering and Technology',
      'PSN Institute of Technology and Science',
      'National College of Engineering',
      'PSN College of Engineering and Technology',
      'PET College of Engineering',
      'S. Veerasamy Chettiar College of Engineering and Technology',
      'Sardar Raja College of Engineering',
      'SCAD College of Engineering and Technology',
      'The Rajaas Engineering College',
      'Government College of Engineering, Tirunelveli',
      'Einstein College of Engineering',
      'PSN Engineering College',
      'JP College of Engineering',
      'Mahakavi Bharathiyar College of Engineering and Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Maanur',
    ],
  },
  {
    district: 'Vellore',
    engineering: [
      'Annai Mira College of Engineering and Technology',
      'C. Abdul Hakeem College of Engineering and Technology',
      'G.G.R. College of Engineering',
      "Ganadipathy Tulsi's Engineering College",
      'Priyadarshini Engineering College',
      'Ranippettai Engineering College',
      'Sri Nandhanam College of Engineering and Technology',
      'Saraswathi Velu College of Engineering',
      'Thanthai Periyar Government Institute of Technology',
      'Bharathidasan Engineering College',
      'Kingston Engineering College',
      'Shri Sapthagiri Institute of Technology',
      'Global Institute of Engineering and Technology',
      'Podhigai College of Engineering and Technology',
      'Sri Krishna College of Engineering',
      "St. John's College of Engineering and Technology for Women",
    ],
    arts_science: [
      'Government Arts and Science College, Serkadu',
    ],
  },
  {
    district: 'Kanchipuram',
    engineering: [
      'University College of Engineering, Kanchipuram',
      'Pallava Raja College of Engineering',
      'Jeppiaar Institute of Technology',
      "St. Joseph's Institute of Technology",
      'Arignar Anna Institute of Science and Technology',
      'DMI College of Engineering',
      'Kalsar College of Engineering',
      'Lord Venkateshwara Engineering College',
      'Maamallan Institute of Technology',
      'Kings Engineering College',
      'Kanchi Pallavan Engineering College',
      'Pallavan College of Engineering',
      'Rajalakshmi Engineering College',
      'Rajiv Gandhi College of Engineering',
      'Sakthi Mariamman Engineering College',
      'Saveetha Engineering College',
      'Sri Muthukumaran Institute of Technology',
      'Sri Venkateswara College of Engineering',
      'PB College of Engineering',
      'PT Lee Chengalvaraya Naicker College of Engineering and Technology',
      'Alpha College of Engineering',
      'Apollo Engineering College',
      'Adhi College of Engineering and Technology',
      'Indira Institute of Engineering and Technology',
      'JEI Mathaajee College of Engineering',
      'KCG College of Technology',
      'SSN College of Engineering',
      "St. Joseph's College of Engineering",
      'Chennai Institute of Technology',
      'Adhiparasakthi Engineering College',
      'Dhanalakshmi College of Engineering',
      'Karpaga Vinayaga College of Engineering and Technology',
      'Sri Venkateswaraa College of Technology',
      'Prince Dr. K. Vasudevan College of Engineering and Technology',
      'Tagore Engineering College',
      'Valliammai Engineering College',
      'Dhaanish Ahmed College of Engineering',
      'Shri Andal Alagar College of Engineering',
      'Prince Shri Venkateshwara Padmavathy Engineering College',
    ],
    arts_science: [
      'Government Arts and Science College, Sriperambatur',
    ],
  },
  {
    district: 'Dharmapuri',
    engineering: [
      'Government College of Engineering, Dharmapuri',
      'Jayam College of Engineering and Technology',
      'Sapthagiri College of Engineering',
      'Jayalakshmi Institute of Technology',
      'Varuvan Vadivelan Institute of Technology',
      'Shreenivasa Engineering College',
    ],
    arts_science: [
      'Government Arts and Science College, Eriyur',
      'Government Arts and Science College, Pennagaram',
      'Government Arts and Science College, Harur',
      'Government Arts and Science College, Pappyreddipatti',
      'Government Arts College, Dharmapuri',
    ],
  },
  {
    district: 'Krishnagiri',
    engineering: [
      'Government College of Engineering, Bargur',
      'Sri Venkateshwara Institute of Engineering',
      'Hosur Institute of Technology and Science',
      'Adhiyamaan College of Engineering',
      'Er. Perumal Manimekalai College of Engineering',
      'P.S.V. College of Engineering and Technology',
      'Archana Institute of Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Hosur',
      'Government Arts and Science College, Thally',
    ],
  },
  {
    district: 'Dindigul',
    engineering: [
      'SSM Institute of Engineering and Technology',
      'Christian College of Engineering and Technology',
      'Sri Subramanya College of Engineering and Technology',
      'N.P.R. College of Engineering and Technology',
      'Pannaikadu Veerammal Paramasivam College of Engineering and Technology for Women',
      'R.V.S. School of Engineering and Technology',
      'Kodaikanal Institute of Technology',
      'PSNA College of Engineering and Technology',
      'SBM College of Engineering and Technology',
      'R.V.S. College of Engineering and Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Oddanchatram',
      'Government Arts and Science College, Reddiarchatram',
      'Government Arts and Science College, Vedasandur',
    ],
  },
  {
    district: 'Karur',
    engineering: [
      'N.S.N. College of Engineering and Technology',
      'Cheran College of Engineering',
      'Arulmuruga Technical Campus',
      'V.S.B. Engineering College',
      'Chettinad College of Engineering and Technology',
      'Karur College of Engineering',
      'V.K.S. College of Engineering and Technology',
      'M. Kumaraswamy College of Engineering',
    ],
    arts_science: [
      'Government Arts and Science College, Aravakurichi',
      'Government Arts and Science College, Tharagampadi',
    ],
  },
  {
    district: 'Cuddalore',
    engineering: [
      'Krishnasamy College of Engineering and Technology',
      'Sri Jayaram Engineering College',
      'Dr. Navalar Nedunchezhiyan College of Engineering',
      'M.R.K. Institute of Technology',
      "St. Anne's College of Engineering and Technology",
    ],
    arts_science: [
      'Government Arts and Science College, Vadalur',
      'Government Arts College, Chidambaram',
    ],
  },
  {
    district: 'Villupuram',
    engineering: [
      'University College of Engineering, Villupuram',
      'University College of Engineering, Tindivanam',
      'Vedhantha Institute of Technology',
      'Annai Teresa College of Engineering',
      "Dr. Paul's Engineering College",
      'I.F.E.T. College of Engineering',
      'Mailam Engineering College',
      'T.S.M. Jain College of Technology',
      'V.R.S. College of Engineering and Technology',
      'E.S. College of Engineering and Technology',
      'Maha Bharathi Engineering College',
      'Sri Aravindar Engineering College',
      'Surya College of Engineering and Technology',
      'A.R. Engineering College',
      'A.K.T. Memorial College of Engineering and Technology',
      'Sri Rangapoopathi College of Engineering',
      'Saraswathy College of Engineering and Technology',
      'Idhaya Engineering College for Women',
    ],
    arts_science: [
      'Arignar Anna Government Arts College, Villupuram',
      'Government Arts and Science College, Gingee',
      'Government Arts and Science College, Tiruvennainallur',
      'Government Arts and Science College, Vanur',
    ],
  },
  {
    district: 'Thoothukudi',
    engineering: [
      'University Vocational College of Engineering, Thoothukudi',
      'V.V. College of Engineering',
      'Chandy College of Engineering',
      'St. Mother Theresa Engineering College',
      'Holy Cross Engineering College',
      'SCAD College of Engineering',
      'Unnamalai Institute of Technology',
      'Dr. Sivanthi Aditanar College of Engineering',
      'Dr. G.U. Pope College of Engineering',
      'Infant Jesus College of Engineering',
      'Jayaraj Annapackiam CSI College of Engineering',
      'Infant Jesus College of Engineering and Technology',
    ],
    arts_science: [
      'Government Arts and Science College, Nagalapuram',
      'Government Arts College, Kovilpatti',
    ],
  },
  {
    district: 'Nagercoil',
    engineering: [
      'University College of Engineering, Nagercoil',
      'Rohini College of Engineering and Technology',
      'Maria College of Engineering and Technology',
      'Mar Ephraem College of Engineering and Technology',
      'M.E.T. Engineering College',
      'Immanuel Arasar J.J. College of Engineering',
      'Sivaji College of Engineering and Technology',
      'Satyam College of Engineering and Technology',
      'Arunachala College of Engineering for Women',
      "Vins Christian Women's College of Engineering",
      'DMI Engineering College',
      'Rajas International Institute of Technology for Women',
      'Tamizhan College of Engineering and Technology',
      'C.S.I. Institute of Technology',
      'Jayamatha Engineering College',
      "St. Xavier's Catholic College of Engineering",
      'Sun College of Engineering and Technology',
      'Narayana Guru College of Engineering',
      'Udaya School of Engineering',
      'Ponjesly College of Engineering',
      'Vins Christian College of Engineering',
      'Lord Jegannath College of Engineering and Technology',
      'Marthandam College of Engineering and Technology',
      'KNSK College of Engineering',
      'James College of Engineering and Technology',
      'Bethlahem Institute of Engineering',
      'Loyola Institute of Technology and Science',
      'Annai Vailankanni College of Engineering',
    ],
    arts_science: [
      'Government Arts and Science College, Nagercoil',
      'Government Arts and Science College, Kanyakumari',
    ],
  },
];

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .substring(0, 40);
}

const institutions = [];
let idCounter = 1;

for (const group of rawDirectory) {
  const district = group.district;
  for (const name of group.engineering) {
    const slug = slugify(name);
    const id = `inst_${slug}_${idCounter++}`;
    // Nandha Engineering College is isOnboarded: true
    const isOnboarded = name.toLowerCase().includes('nandha engineering college');
    institutions.push({
      id,
      name,
      institutionType: 'engineering',
      district,
      sourceType: 'TNEA',
      isActive: true,
      isOnboarded,
    });
  }

  for (const name of group.arts_science) {
    const slug = slugify(name);
    const id = `inst_${slug}_${idCounter++}`;
    institutions.push({
      id,
      name,
      institutionType: 'arts_science',
      district,
      sourceType: 'TNGASA_DCE',
      isActive: true,
      isOnboarded: false,
    });
  }
}

console.log(`Parsed ${institutions.length} institutions across ${rawDirectory.length} districts.`);
const onboardedCount = institutions.filter(i => i.isOnboarded).length;
console.log(`Onboarded institutions: ${onboardedCount}`);

fs.writeFileSync(
  path.join(__dirname, 'parsed_institutions.json'),
  JSON.stringify(institutions, null, 2),
  'utf-8'
);
